# Tarea: Aprendizaje por Refuerzo

1. Dado el mundo definido por la siguiente función de transición $f_{M_{T}} (s, a)$, la función de recompensa $f_{R}(s, a, s_{f} ) = f_{R}( sf )$ y $\gamma = 0.9$:

$
 f_{M_{T}} = \begin{matrix}
             & \begin{matrix}a1 & a2\end{matrix} \\
             \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \\ s_{4} \end{matrix} &
             \begin{bmatrix}
             s_{2} & s_{2} \\
             s_{1} & s_{3} \\
             s_{3} & s_{1} \\
             s_{1} & s_{4} \\
             \end{bmatrix}
            \end{matrix}
$
$ 
 f_{R}(s_{f}) = \begin{matrix}
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \\ s_{4} \end{matrix} 
                    &
                    \begin{bmatrix} 2 \\ 1 \\ -1 \\ 10 \end{bmatrix}
                \end{matrix}
$

In [1]:
import numpy as np

fmt: np.ndarray = np.array([
    np.array([2, 2]),
    np.array([1, 3]),
    np.array([3, 1]),
    np.array([1, 4]),
])
fr = [2, 1, -1, 10]
gamma = .9

a. Resuelva las Ecuaciones de Optimalidad de Bellman por Iteración de Valor para V(s).

In [2]:
a_size = len(fr)
vs = np.zeros(a_size)
iteration = 0
while True:
    i = 0
    new_vs = np.zeros(a_size)
    for s in fmt:
        a1, a2 = s
        vsi = [fr[a1-1] + (gamma * vs[a1-1]), fr[a2-1] + (gamma * vs[a2-1])]
        new_vs[i] = max(vsi)
        i += 1
    diff = new_vs - vs
    if len(diff[diff>.1]) == 0:
        print(iteration, new_vs)
        break
    vs = new_vs
    iteration += 1

44 [14.60362582 15.13453527 15.13453527 99.12720364]


b. Resuelva las Ecuaciones de Optimalidad de Bellman por Iteración de Valor para Q(s,a).

In [3]:
import numpy as np

m, n = fmt.shape
qsa = np.zeros((m, n))
iteration = 0
while True:
    new_qsa = []
    for i in range(m):
        idx1, idx2 = fmt[i]
        r1 = fr[idx1-1] + (gamma * max(qsa[idx1-1]))
        r2 = fr[idx2-1] + (gamma * max(qsa[idx2-1]))
        new_qsa.append(np.array([r1, r2]))
    new_qsa_n = np.array(new_qsa)
    diff = new_qsa_n - qsa
    flags = []
    for r in diff:
        flag = True
        if len(r[r>.1]) == 0:
            flag = False
        flags.append(flag)
    if sum(flags) == 0:
        print(iteration, new_qsa_n.T)
        break
    qsa = new_qsa_n
    iteration += 1
    

44 [[14.60362582 15.13453527 12.60362582 15.13453527]
 [14.60362582 12.60362582 15.13453527 99.12720364]]


2. Dado el mundo definido por la función de transición $P_{M_{T}}(s_{f}|s,a)$ la función de recompensa $f_{R}(s,a,s_{f})=f_{R}(s_{f})$ y $\gamma=0.6$:

$
 f_{M_{T}} = \begin{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{1} \\ \begin{matrix}a_{1} & a_{2}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \end{matrix} &
                    \begin{bmatrix}
                        0.4 & 0.2 \\
                        0.5 & 0.0 \\
                        1.0 & 0.3 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{2} \\ \begin{matrix}a_{1} & a_{2}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \end{matrix} &
                    \begin{bmatrix}
                        0.5 & 0.8 \\
                        0.0 & 0.0 \\
                        0.0 & 0.6 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{3} \\ \begin{matrix}a_{1} & a_{2}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \end{matrix} &
                    \begin{bmatrix}
                        0.1 & 0.0 \\
                        0.5 & 1.0 \\
                        0.0 & 0.1 \\
                    \end{bmatrix}
                \end{matrix}
            \end{matrix}
$

$ 
 f_{R}(s_{f}) = \begin{matrix}
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \end{matrix} 
                    &
                    \begin{bmatrix} 2 \\ 1 \\ -1 \end{bmatrix}
                \end{matrix}
$

In [4]:
fmt = [[
    [0.4, 0.2],
    [0.5, 0.0],
    [1.0, 0.3],
],[
    [0.5, 0.8],
    [0.0, 0.0],
    [0.0, 0.6],
],[
    [0.1, 0.0],
    [0.5, 1.0],
    [0.0, 0.1],
]]
fr = [2, 1, -1]
gamma = .6

a. Resuelva las Ecuaciones de Optimalidad de Bellman por Iteración de Valor para V(s).

In [7]:
m = len(fmt)
n = len(fmt[0])
vs = np.zeros(n)
iteration = 0
while True:
    new_vs = vs.copy()
    for si in range(n):
        r1 = 0
        r2 = 0
        for sfi in range(m):
            r1 += fmt[sfi][si][0] * (fr[sfi] + (gamma * vs[sfi]))
            r2 += fmt[sfi][si][1] * (fr[sfi] + (gamma * vs[sfi]))
        new_vs[si] = max([r1, r2])
    print(iteration, new_vs)
    diff = new_vs - vs
    if len(diff[diff>.1]) == 0:
        break
    vs = new_vs.copy()
    iteration += 1

0 [1.2 0.5 2. ]
1 [1.758 1.46  2.72 ]
2 [2.22312 1.8434  3.0548 ]
3 [2.4698568 2.083376  3.333872 ]
4 [2.61781075 2.24111864 3.48191408]
5 [2.70952502 2.32991745 3.57068645]


b. Resuelva las Ecuaciones de Optimalidad de Bellman por Iteración de Valor para Q(s,a).

In [22]:
m = len(fmt)
n = len(fmt[0])
w = len(fmt[0][0])
qsa = np.zeros((n, w))
iteration = 0
while True:
    new_qsa = np.zeros((n, w))
    for si in range(n):
        r1 = 0
        r2 = 0
        for sfi in range(m):
            r1 += fmt[sfi][si][0] * (fr[sfi] + (gamma * max(qsa[sfi])))
            r2 += fmt[sfi][si][1] * (fr[sfi] + (gamma * max(qsa[sfi])))
        new_qsa[si, 0] = r1
        new_qsa[si, 1] = r2
    print(iteration)
    print(new_qsa.T)
    diff = new_qsa - qsa
    flags = []
    for r in diff:
        flag = True
        if len(r[r>.1]) == 0:
            flag = False
        flags.append(flag)
    if sum(flags) == 0:
        break
    qsa = new_qsa
    iteration += 1

0
[[ 1.2  0.5  2. ]
 [ 1.2 -1.   1.1]]
1
[[1.758 1.46  2.72 ]
 [1.584 0.2   1.616]]
2
[[2.22312 1.8434  3.0548 ]
 [2.11176 0.632   2.10524]]
3
[[2.4698568 2.083376  3.333872 ]
 [2.3516064 0.83288   2.3470736]]
4
[[2.61781075 2.24111864 3.48191408]
 [2.4964033  1.0003232  2.4946219 ]]
5
[[2.70952502 2.32991745 3.57068645]
 [2.58987424 1.08914845 2.58692349]]
