# Tarea: Aprendizaje por Refuerzo

1. Dado el mundo definido por la siguiente función de transición $f_{M_{T}} (s, a)$, la función de recompensa $f_{R}(s, a, s_{f} ) = f_{R}( sf )$ y $\gamma = 0.9$:

$
 f_{M_{T}} = \begin{matrix}
             & \begin{matrix}a1 & a2\end{matrix} \\
             \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \\ s_{4} \end{matrix} &
             \begin{bmatrix}
             s_{2} & s_{2} \\
             s_{1} & s_{3} \\
             s_{3} & s_{1} \\
             s_{1} & s_{4} \\
             \end{bmatrix}
            \end{matrix}
$
$ 
 f_{R}(s_{f}) = \begin{matrix}
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \\ s_{4} \end{matrix} 
                    &
                    \begin{bmatrix} 2 \\ 1 \\ -1 \\ 10 \end{bmatrix}
                \end{matrix}
$

In [107]:
import numpy as np

fmt: np.ndarray = np.array([
    np.array([2, 2]),
    np.array([1, 3]),
    np.array([3, 1]),
    np.array([1, 4]),
])
fr = [2, 1, -1, 10]
gamma = .9

a. Resuelva las Ecuaciones de Optimalidad de Bellman por Iteración de Valor para V(s).

In [108]:
a_size = len(fr)
vs = np.zeros(a_size)
iteration = 0
while True:
    i = 0
    new_vs = np.zeros(a_size)
    for s in fmt:
        a1, a2 = s
        vsi = [fr[a1-1] + (gamma * vs[a1-1]), fr[a2-1] + (gamma * vs[a2-1])]
        new_vs[i] = max(vsi)
        i += 1
    print(iteration, new_vs)
    diff = new_vs - vs
    if len(diff[diff>.1]) == 0:
        break
    vs = new_vs
    iteration += 1

0 [ 1.  2.  2. 10.]
1 [ 2.8  2.9  2.9 19. ]
2 [ 3.61  4.52  4.52 27.1 ]
3 [ 5.068  5.249  5.249 34.39 ]
4 [ 5.7241  6.5612  6.5612 40.951 ]
5 [ 6.90508  7.15169  7.15169 46.8559 ]
6 [ 7.436521  8.214572  8.214572 52.17031 ]
7 [ 8.3931148  8.6928689  8.6928689 56.953279 ]
8 [ 8.82358201  9.55380332  9.55380332 61.2579511 ]
9 [ 9.59842299  9.94122381  9.94122381 65.13215599]
10 [ 9.94710143 10.63858069 10.63858069 68.61894039]
11 [10.57472262 10.95239129 10.95239129 71.75704635]
12 [10.85715216 11.51725036 11.51725036 74.58134172]
13 [11.36552532 11.77143694 11.77143694 77.12320755]
14 [11.59429325 12.22897279 12.22897279 79.41088679]
15 [12.00607551 12.43486392 12.43486392 81.46979811]
16 [12.19137753 12.80546796 12.80546796 83.3228183 ]
17 [12.52492116 12.97223978 12.97223978 84.99053647]
18 [12.6750158  13.27242905 13.27242905 86.49148282]
19 [12.94518614 13.40751422 13.40751422 87.84233454]
20 [13.0667628  13.65066753 13.65066753 89.05810109]
21 [13.28560078 13.76008652 13.76008652 9

b. Resuelva las Ecuaciones de Optimalidad de Bellman por Iteración de Valor para Q(s,a).

In [109]:
import numpy as np

m, n = fmt.shape
qsa = np.zeros((m, n))
iteration = 0
while True:
    new_qsa = []
    for i in range(m):
        idx1, idx2 = fmt[i]
        r1 = fr[idx1-1] + (gamma * max(qsa[idx1-1]))
        r2 = fr[idx2-1] + (gamma * max(qsa[idx2-1]))
        new_qsa.append(np.array([r1, r2]))
    new_qsa_n = np.array(new_qsa)
    diff = new_qsa_n - qsa
    flags = []
    for r in diff:
        flag = True
        if len(r[r>.1]) == 0:
            flag = False
        flags.append(flag)
    print(iteration, new_qsa_n.T)
    if sum(flags) == 0:
        break
    qsa = new_qsa_n
    iteration += 1
    

0 [[ 1.  2. -1.  2.]
 [ 1. -1.  2. 10.]]
1 [[ 2.8  2.9  0.8  2.9]
 [ 2.8  0.8  2.9 19. ]]
2 [[ 3.61  4.52  1.61  4.52]
 [ 3.61  1.61  4.52 27.1 ]]
3 [[ 5.068  5.249  3.068  5.249]
 [ 5.068  3.068  5.249 34.39 ]]
4 [[ 5.7241  6.5612  3.7241  6.5612]
 [ 5.7241  3.7241  6.5612 40.951 ]]
5 [[ 6.90508  7.15169  4.90508  7.15169]
 [ 6.90508  4.90508  7.15169 46.8559 ]]
6 [[ 7.436521  8.214572  5.436521  8.214572]
 [ 7.436521  5.436521  8.214572 52.17031 ]]
7 [[ 8.3931148  8.6928689  6.3931148  8.6928689]
 [ 8.3931148  6.3931148  8.6928689 56.953279 ]]
8 [[ 8.82358201  9.55380332  6.82358201  9.55380332]
 [ 8.82358201  6.82358201  9.55380332 61.2579511 ]]
9 [[ 9.59842299  9.94122381  7.59842299  9.94122381]
 [ 9.59842299  7.59842299  9.94122381 65.13215599]]
10 [[ 9.94710143 10.63858069  7.94710143 10.63858069]
 [ 9.94710143  7.94710143 10.63858069 68.61894039]]
11 [[10.57472262 10.95239129  8.57472262 10.95239129]
 [10.57472262  8.57472262 10.95239129 71.75704635]]
12 [[10.85715216 11.517250

2. Dado el mundo definido por la función de transición $P_{M_{T}}(s_{f}|s,a)$ la función de recompensa $f_{R}(s,a,s_{f})=f_{R}(s_{f})$ y $\gamma=0.6$:

$
 f_{M_{T}} = \begin{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{1} \\ \begin{matrix}a_{1} & a_{2}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \end{matrix} &
                    \begin{bmatrix}
                        0.4 & 0.2 \\
                        0.5 & 0.0 \\
                        1.0 & 0.3 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{2} \\ \begin{matrix}a_{1} & a_{2}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \end{matrix} &
                    \begin{bmatrix}
                        0.5 & 0.8 \\
                        0.0 & 0.0 \\
                        0.0 & 0.6 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{3} \\ \begin{matrix}a_{1} & a_{2}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \end{matrix} &
                    \begin{bmatrix}
                        0.1 & 0.0 \\
                        0.5 & 1.0 \\
                        0.0 & 0.1 \\
                    \end{bmatrix}
                \end{matrix}
            \end{matrix}
$

$ 
 f_{R}(s_{f}) = \begin{matrix}
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \end{matrix} 
                    &
                    \begin{bmatrix} 2 \\ 1 \\ -1 \end{bmatrix}
                \end{matrix}
$

In [110]:
fmt = [[
    [0.4, 0.2],
    [0.5, 0.0],
    [1.0, 0.3],
],[
    [0.5, 0.8],
    [0.0, 0.0],
    [0.0, 0.6],
],[
    [0.1, 0.0],
    [0.5, 1.0],
    [0.0, 0.1],
]]
fr = [2, 1, -1]
gamma = .6

a. Resuelva las Ecuaciones de Optimalidad de Bellman por Iteración de Valor para V(s).

In [111]:
m = len(fmt)
n = len(fmt[0])
vs = np.zeros(n)
iteration = 0
while True:
    new_vs = vs.copy()
    for si in range(n):
        r1 = 0
        r2 = 0
        for sfi in range(m):
            r1 += fmt[sfi][si][0] * (fr[sfi] + (gamma * vs[sfi]))
            r2 += fmt[sfi][si][1] * (fr[sfi] + (gamma * vs[sfi]))
        new_vs[si] = max([r1, r2])
    print(iteration, new_vs)
    diff = new_vs - vs
    if len(diff[diff>.1]) == 0:
        break
    vs = new_vs.copy()
    iteration += 1

0 [1.2 0.5 2. ]
1 [1.758 1.46  2.72 ]
2 [2.22312 1.8434  3.0548 ]
3 [2.4698568 2.083376  3.333872 ]
4 [2.61781075 2.24111864 3.48191408]
5 [2.70952502 2.32991745 3.57068645]


b. Resuelva las Ecuaciones de Optimalidad de Bellman por Iteración de Valor para Q(s,a).

In [112]:
m = len(fmt)
n = len(fmt[0])
w = len(fmt[0][0])
qsa = np.zeros((n, w))
iteration = 0
while True:
    new_qsa = np.zeros((n, w))
    for si in range(n):
        r1 = 0
        r2 = 0
        for sfi in range(m):
            r1 += fmt[sfi][si][0] * (fr[sfi] + (gamma * max(qsa[sfi])))
            r2 += fmt[sfi][si][1] * (fr[sfi] + (gamma * max(qsa[sfi])))
        new_qsa[si, 0] = r1
        new_qsa[si, 1] = r2
    print(iteration)
    print(new_qsa.T)
    diff = new_qsa - qsa
    flags = []
    for r in diff:
        flag = True
        if len(r[r>.1]) == 0:
            flag = False
        flags.append(flag)
    if sum(flags) == 0:
        break
    qsa = new_qsa
    iteration += 1

0
[[ 1.2  0.5  2. ]
 [ 1.2 -1.   1.1]]
1
[[1.758 1.46  2.72 ]
 [1.584 0.2   1.616]]
2
[[2.22312 1.8434  3.0548 ]
 [2.11176 0.632   2.10524]]
3
[[2.4698568 2.083376  3.333872 ]
 [2.3516064 0.83288   2.3470736]]
4
[[2.61781075 2.24111864 3.48191408]
 [2.4964033  1.0003232  2.4946219 ]]
5
[[2.70952502 2.32991745 3.57068645]
 [2.58987424 1.08914845 2.58692349]]


3. Dado el mundo definido por el siguiente grafo, la siguiente función de recompensa $f_{R}(s,a,s_{f})$
y $\gamma=0.8$:

![figure-1](./images/figure-1.png)

$
 f_{M_{T}} = \begin{matrix}
             & \begin{matrix}a1 & a2 & a3\end{matrix} \\
             \begin{matrix} s_{1} \\ s_{2} \\ s_{3} \\ s_{4} \\ s_{5} \end{matrix} &
             \begin{bmatrix}
             s_{2} & s_{3} & s_{4} \\
              & s_{3} &  \\
              &  & s_{5} \\
              & s_{3} &  \\
             s_{4} &  &  \\
             \end{bmatrix}
            \end{matrix}
$

$
 f_{R}(s,a,s_{f}) = \begin{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{1} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{2} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        -2 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{3} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        0 & 5 & 0 \\
                        0 & 4 & 0 \\
                        0 & 0 & 0 \\
                        0 & -1 & 0 \\
                        0 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{4} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        0 & 0 & -3 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        1 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{5} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & -6 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
            \end{matrix}
$

In [113]:
fmt = [
    [2,3,4],
    [0,3,0],
    [0,0,5],
    [0,3,0],
    [4,0,0],
]

fr = [[
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
],[ 
    [-2, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
],[ 
    [0, 5, 0],
    [0, 4, 0],
    [0, 0, 0],
    [0, -1, 0],
    [0, 0, 0],
],[ 
    [0, 0, -3],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [1, 0, 0],
],[ 
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, -6],
    [0, 0, 0],
    [0, 0, 0],
]]

gamma = .8

In [114]:
m = len(fr)
n = len(fr[0])
w = len(fr[0][0])
vs: np.ndarray = np.zeros(m)
iteration = 0

while True:
    new_vs: np.ndarray = vs.copy()
    for si in range(n):
        r: np.ndarray = np.zeros(m)
        a_sf: list = fmt[si].copy()
        r = []
        for ai in range(w):
            sf_idx = fmt[si][ai]-1
            if sf_idx != -1:
                ri = fr[sf_idx][si][ai] + (gamma * vs[sf_idx])
                r.append(ri)
        new_vs[si] = max(r)
    print(iteration, new_vs)
    diff = new_vs - vs
    if len(diff[diff>.1]) == 0:
        break
    vs = new_vs.copy()
    iteration += 1

0 [ 5.  4. -6. -1.  1.]
1 [ 1.2 -0.8 -5.2 -5.8  0.2]
2 [ 0.84 -0.16 -5.84 -5.16 -3.64]
3 [ 0.328 -0.672 -8.912 -5.672 -3.128]
4 [-2.1296 -3.1296 -8.5024 -8.1296 -3.5376]
5 [-1.80192 -2.80192 -8.83008 -7.80192 -5.50368]
6 [ -2.064064  -3.064064 -10.402944  -8.064064  -5.241536]
7 [ -3.3223552  -4.3223552 -10.1932288  -9.3223552  -5.4512512]
8 [ -3.15458304  -4.15458304 -10.36100096  -9.15458304  -6.45788416]
9 [ -3.28880077  -4.28880077 -11.16630733  -9.28880077  -6.32366643]
10 [ -3.93304586  -4.93304586 -11.05893315  -9.93304586  -6.43104061]
11 [ -3.84714652  -4.84714652 -11.14483249  -9.84714652  -6.94643669]


b. Resuelva las Ecuaciones de Optimalidad de Bellman por Iteración de Valor para Q(s,a).

In [115]:
qsa: np.ndarray = np.zeros((m, w))
iteration = 0

while True:
    new_qsa: np.ndarray = qsa.copy()
    for si in range(n):
        a_sf = fmt[si]
        r = []
        for ai in range(len(a_sf)):
            sf_idx = a_sf[ai]-1
            ri = fr[sf_idx][si][ai] + (gamma * max(qsa[sf_idx]))
            r.append(ri)
        new_qsa[si] = np.array(r)
    print(iteration)
    print(new_qsa.T)
    diff = new_qsa - qsa
    flags = []
    for r in diff:
        flag = True
        if len(r[r>.1]) == 0:
            flag = False
        flags.append(flag)
    if sum(flags) == 0:
        break
    qsa = new_qsa
    iteration += 1

0
[[-2.  0.  0.  0.  1.]
 [ 5.  4.  0. -1.  0.]
 [-3.  0. -6.  0.  0.]]
1
[[ 1.2  0.8  0.8  0.8  1. ]
 [ 5.   4.   0.8 -1.   0.8]
 [-3.   0.8 -5.2  0.8  0.8]]
2
[[ 1.2   0.8   0.8   0.8   1.64]
 [ 5.64  4.64  0.8  -0.36  0.8 ]
 [-2.36  0.8  -5.2   0.8   0.8 ]]
3
[[ 1.712  1.312  1.312  1.312  1.64 ]
 [ 5.64   4.64   1.312 -0.36   1.312]
 [-2.36   1.312 -4.688  1.312  1.312]]
4
[[ 1.712   1.312   1.312   1.312   2.0496]
 [ 6.0496  5.0496  1.312   0.0496  1.312 ]
 [-1.9504  1.312  -4.688   1.312   1.312 ]]
5
[[ 2.03968  1.63968  1.63968  1.63968  2.0496 ]
 [ 6.0496   5.0496   1.63968  0.0496   1.63968]
 [-1.9504   1.63968 -4.36032  1.63968  1.63968]]
6
[[ 2.03968   1.63968   1.63968   1.63968   2.311744]
 [ 6.311744  5.311744  1.63968   0.311744  1.63968 ]
 [-1.688256  1.63968  -4.36032   1.63968   1.63968 ]]
7
[[ 2.2493952  1.8493952  1.8493952  1.8493952  2.311744 ]
 [ 6.311744   5.311744   1.8493952  0.311744   1.8493952]
 [-1.688256   1.8493952 -4.1506048  1.8493952  1.8493952]]
8
[[

4. Dado el mundo definido por el siguiente grafo donde 0.8a1 significa a1 con probabilidad 0.8, 1a2 significa a2 con probabilidad 1, y así sucesivamente, y con la siguiente función de recompensa $f_{R}(s,a,s_{f})$ y $\gamma=0.7$:

![figure-1](./images/figure-1.png)

$
 f_{M_{T}} = \begin{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{1} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{2} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        0 & 1 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & .2 & 0 \\
                        0 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{3} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        0 & 0 & 0 \\
                        0 & 0 & .4 \\
                        0 & 0 & 0 \\
                        0 & .8 & 0 \\
                        0 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{4} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        .2 & 0 & 0 \\
                        0 & 0 & .3 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 1 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{5} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        .8 & 0 & 0 \\
                        0 & 0 & .3 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
            \end{matrix}
$

$
 f_{R}(s,a,s_{f}) = \begin{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{1} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        9 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 1 & 0 \\
                        0 & 0 & -2 \\
                        2 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{2} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        -2 & 2 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & -3 & 0 \\
                        0 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{3} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        0 & 5 & 0 \\
                        0 & 4 & -1 \\
                        0 & 0 & 0 \\
                        0 & -1 & 0 \\
                        0 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{4} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        1 & 0 & -3 \\
                        0 & 0 & 2 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                        1 & -1 & 0 \\
                    \end{bmatrix}
                \end{matrix}
                \begin{matrix}
                    & \begin{matrix} s_{f}=s_{5} \\ \begin{matrix}a_{1} & a_{2} & a_{3}\end{matrix} \end{matrix} \\
                    \begin{matrix} s_{1} \\ s_{2} \\ s_{3}  \\ s_{4}  \\ s_{5} \end{matrix} &
                    \begin{bmatrix}
                        3 & 0 & 0 \\
                        0 & 0 & 0 \\
                        0 & 0 & -6 \\
                        0 & 0 & 0 \\
                        0 & 0 & 0 \\
                    \end{bmatrix}
                \end{matrix}
            \end{matrix}
$

In [116]:
fmt = [[
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
],[ 
    [0, 1, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, .2, 0],
    [0, 0, 0],
],[ 
    [0, 0, 0],
    [0, 0, .4],
    [0, 0, 0],
    [0, .8, 0],
    [0, 0, 0],
],[ 
    [.2, 0, 0],
    [0, 0, .3],
    [0, 0, 0],
    [0, 0, 0],
    [0, 1, 0],
],[ 
    [.8, 0, 0],
    [0, 0, .3],
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
]]

fr = [[
    [9, 0, 0],
    [0, 0, 0],
    [0, 1, 0],
    [0, 0, -2],
    [2, 0, 0],
],[ 
    [-2, 2, 0],
    [0, 0, 0],
    [0, 0, 0],
    [0, -3, 0],
    [0, 0, 0],
],[ 
    [0, 5, 0],
    [0, 4, -1],
    [0, 0, 0],
    [0, -1, 0],
    [0, 0, 0],
],[ 
    [1, 0, -3],
    [0, 0, 2],
    [0, 0, 0],
    [0, 0, 0],
    [1, -1, 0],
],[ 
    [3, 0, 0],
    [0, 0, 0],
    [0, 0, -6],
    [0, 0, 0],
    [0, 0, 0],
]]

gamma = .8

a. Resuelva las Ecuaciones de Optimalidad de Bellman por Iteración de Valor para V(s).


b. Resuelva las Ecuaciones de Optimalidad de Bellman por Iteración de Valor para Q(s,a).